### ISSUE TITLE
LSM303DLHC_AccReadXYZ doesn't properly gives mg values

### ISSUE THREAD

**Issue by JoaoVictor0508** [STMicroelectronics/lsm303dlhc#1]
**Describe the set-up**

 * Using the STM32F411E-Disco
 * STM32CubeIDE 1.14.0

**Describe the bug (skip if none)**

According to the code below, it's clear that the data is given in mg, but when you see the data it's in LSB instead.

```
  /* Obtain the mg value for the three axis */
  for(i=0; i<3; i++)
  {
    pData[i]=(pnRawData[i] * sensitivity);
  }
```
I know it can be just a user problem, but as it's the first time I am using these sensor, I was hoping that the function would provide me the data in mg. When I used the debug tool I saw a value around 15500 in the Z axis and I really thought I was doing something wrong.

**Additional context**

In the case, so that the values can be properly given in mg, the following values should be used for the sensitivity.

![image](https://github.com/STMicroelectronics/stm32-lsm303dlhc/assets/110051762/46f914f2-06b6-4b5e-bf42-bc379041c74c)

**Comment by ASEHSTM** [comment]
Hello @JoaoVictor0508,

Thank you for your report. I would like to clarify that the sensitivity setting for this driver is `LSM303DLHC_ACC_SENSITIVITY_2G`, which corresponds to 1 [mg/LSB]. This means that the mg and LSB values are equivalent.

Please find below the sensitivity values from the LSM303DLHC datasheet and the corresponding sensitivity definitions from the lsm303dlhc.h file:
![image (2)](https://github.com/STMicroelectronics/stm32-lsm303dlhc/assets/160479079/29df51f0-18d9-4dd3-8b9d-18b4d5495dff)
![image (1)](https://github.com/STMicroelectronics/stm32-lsm303dlhc/assets/160479079/9887f76c-70bb-4dbd-ac53-67c36d638070)

With Regards,
